### ISSUE TITLE
No puedo clonar el repositorio

### ISSUE THREAD

**Issue by LuisBrime** [A01334390/Nova#1]
Dice que un archivo del conector de java=sql tiene un nombre o un path demasiado largo.
Help :(

**Comment by ghost** [comment]
@LuisBrime ¿Podrías subir una foto donde se muestra el problema?

**Comment by LuisBrime** [comment]
![image](https://user-images.githubusercontent.com/23020655/38215820-96a6217a-368e-11e8-8b5b-f81e33013449.png)

**Comment by LuisBrime** [comment]
@A01334390

**Comment by ghost** [comment]
Listo, intentalo otra vez.

**Comment by ghost** [comment]
Se elimino la documentación del conector de MySQL que era problemática
